/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/node/config/del/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Удаление конфигурации */
        post: operations["node_config_del"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/config/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список конфигураций */
        get: operations["node_config_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/config/put/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сохранение конфигурации */
        post: operations["node_config_put"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/config/read/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение конфигурации */
        get: operations["node_config_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/module/add/{reg}/{mod}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Добавление модуля из реестра */
        get: operations["node_module_add"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/module/cp/{modfr}/{modto}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Копирование модуля */
        get: operations["node_module_cp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/module/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список модулей на ноде */
        get: operations["node_module_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/module/onreg/{reg}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список модулей из реестра */
        get: operations["node_module_onreg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/module/rm/{mod}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Удаление модуля */
        get: operations["node_module_rm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/register/del/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Удаление реестра */
        post: operations["node_register_del"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/register/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список реестров */
        get: operations["node_register_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/register/put/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сохранение реестра */
        post: operations["node_register_put"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/register/read/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение реестра */
        get: operations["node_register_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/running": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список запущенных сервисов */
        get: operations["node_running"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/service/del/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Удаление сервиса */
        post: operations["node_service_del"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/service/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список сервисов */
        get: operations["node_service_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/service/put/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сохранение сервиса */
        post: operations["node_service_put"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/service/read/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение сервиса */
        get: operations["node_service_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/start/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Запуск сервиса */
        get: operations["node_start"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/start_all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Запуск всех сервисов */
        get: operations["node_start_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/stop/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Остановка сервиса */
        get: operations["node_stop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/stop_all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Остановка всех сервисов */
        get: operations["node_stop_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/config/del/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Удаление конфигурации из реестра */
        post: operations["reg_config_del"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/config/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список конфигураций в реестре */
        get: operations["reg_config_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/config/put/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сохранение конфигурации в реестр */
        post: operations["reg_config_put"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/config/read/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение конфигурации из реестра */
        get: operations["reg_config_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/module/del/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Удаление модуля из реестра */
        post: operations["reg_module_del"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/module/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список модулей в реестре */
        get: operations["reg_module_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/module/put/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сохранение модуля в реестр */
        post: operations["reg_module_put"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reg/module/read/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение модуля из реестра */
        get: operations["reg_module_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActMod
         * @description Подключаемый модуль системы
         */
        ActMod: {
            /** @description Программный код модуля (Elixir => base64) */
            base64?: string;
            /** @description Конфигурация по умолчанию */
            config_default?: Record<string, never>;
            /** @description URL реестра, откуда получен модуль */
            from_reg?: string;
            /** ActMod_ID */
            id?: string;
        };
        /**
         * ActModConf
         * @description Конфигурация
         */
        ActModConf: {
            /** ActModConf_ID */
            id?: string;
            /** @description Параметры */
            params?: Record<string, never>;
        };
        /**
         * ActModConf_ID
         * @description ИД используемой конфигурации (можно не указывать, тогда создастся автоматически)
         */
        ActModConf_ID: string;
        /**
         * ActMod_ID
         * @description ИД используемого модуля
         */
        ActMod_ID: string;
        /**
         * ActServ
         * @description Запускаемый сервис системы
         */
        ActServ: {
            /**
             * Service_channels
             * @description Каналы сервиса (входные и выходные). Следует иметь ввиду, что порядок указания каналов может быть важен для модуля
             */
            channels?: {
                /** @description Входные каналы */
                in?: string[];
                /** @description Выходные каналы */
                out?: string[];
            };
            /**
             * ActModConf_ID
             * @description ИД используемой конфигурации (можно не указывать, тогда создастся автоматически)
             */
            config?: string;
            /** @description Установленные параметры */
            config_data?: Record<string, never>;
            /** ActServ_ID */
            id?: string;
            /**
             * ActMod_ID
             * @description ИД используемого модуля
             */
            module?: string;
        };
        /** ActServ_ID */
        ActServ_ID: string;
        /**
         * Channel
         * @description Канал
         */
        Channel: string;
        /**
         * OK_response
         * @description OK
         */
        OK_response: string;
        /**
         * Register
         * @description Внешний подключаемый реестр модулей, конфигураций и энтити
         */
        Register: {
            /** Register_ID */
            id?: string;
            /** @description URL подключаемого реестра */
            url?: string;
        };
        /** Register_ID */
        Register_ID: string;
        /**
         * Service_channels
         * @description Каналы сервиса (входные и выходные). Следует иметь ввиду, что порядок указания каналов может быть важен для модуля
         */
        Service_channels: {
            /** @description Входные каналы */
            in?: string[];
            /** @description Выходные каналы */
            out?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    node_config_del: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалённый объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActModConf"];
                };
            };
        };
    };
    node_config_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Массив объектов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActModConf"][];
                };
            };
        };
    };
    node_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActModConf"];
            };
        };
        responses: {
            /** @description Сохранённый ИД */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Не удалось сохранить объект */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    node_config_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActModConf"];
                };
            };
        };
    };
    node_module_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД реестра */
                reg: string;
                /** @description ИД добавляемого модуля */
                mod: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Добавленный модуль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"];
                };
            };
        };
    };
    node_module_cp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД модуля для копирования */
                modfr: string;
                /** @description Новый ИД для копии модуля */
                modto: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Скопированный модуль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"];
                };
            };
        };
    };
    node_module_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Модули */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"][];
                };
            };
        };
    };
    node_module_onreg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД реестра */
                reg: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Модули */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"][];
                };
            };
        };
    };
    node_module_rm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД модуля */
                mod: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалённый модуль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"];
                };
            };
        };
    };
    node_register_del: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалённый объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    node_register_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Массив объектов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"][];
                };
            };
        };
    };
    node_register_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
            };
        };
        responses: {
            /** @description Сохранённый ИД */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Не удалось сохранить объект */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    node_register_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    node_running: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выполняются сервисы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActServ"][];
                };
            };
        };
    };
    node_service_del: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалённый объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActServ"];
                };
            };
        };
    };
    node_service_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Массив объектов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActServ"][];
                };
            };
        };
    };
    node_service_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActServ"];
            };
        };
        responses: {
            /** @description Сохранённый ИД */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Не удалось сохранить объект */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    node_service_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActServ"];
                };
            };
        };
    };
    node_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД сервиса */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выполняются сервисы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActServ"][];
                };
            };
        };
    };
    node_start_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выполнен запуск всех сервисов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    node_stop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД сервиса */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выполняются сервисы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActServ"][];
                };
            };
        };
    };
    node_stop_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все сервисы остановлены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    reg_config_del: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалённый объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActModConf"];
                };
            };
        };
    };
    reg_config_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Массив объектов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActModConf"][];
                };
            };
        };
    };
    reg_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActModConf"];
            };
        };
        responses: {
            /** @description Сохранённый ИД */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Не удалось сохранить объект */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reg_config_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActModConf"];
                };
            };
        };
    };
    reg_module_del: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалённый объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"];
                };
            };
        };
    };
    reg_module_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Массив объектов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"][];
                };
            };
        };
    };
    reg_module_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActMod"];
            };
        };
        responses: {
            /** @description Сохранённый ИД */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Не удалось сохранить объект */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reg_module_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ИД */
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Объект */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActMod"];
                };
            };
        };
    };
}
